CREATE DATABASE IF NOT EXISTS ovotest;
USE ovotest;
CREATE TABLE IF NOT EXISTS daily_reward (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reward_date DATE NOT NULL,
    reward_amount DECIMAL(9,0) NOT NULL DEFAULT 0
) ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    fullname VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(username)
) ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS user_rewards (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    reward_date DATE NOT NULL,
    min_amount DECIMAL(9,0) NOT NULL DEFAULT 0,
    max_amount DECIMAL(9,0) NOT NULL DEFAULT 0,
    reward_amount DECIMAL(9,0) NOT NULL DEFAULT 0,
    actual_amount DECIMAL(9,0) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (username)
        REFERENCES users (username)
        ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=INNODB;